#! /bin/bash
# 
# created by Jonathan Dinh
# uses if, case, select, read, and more
# calculator script for adding, subtracting, multiplying, dividing
calc_menu () {
echo "Welcome to Jonathan's Calculator!"
echo "------------------------------"
echo "This utility allows you to calculate sums, differences, products, and quotients"
cat <<END
	   Menu
---------------------------------------
	1. Add
	2. Subtract
	3. Multiply
	4. Divide
        5. Exit
---------------------------------------
END
PS3="Please press a number for what you would like to do: "
        select choice in 1 2 3 4 5
           do
                case $choice in
                        1)
			check_args
                        add
                        ;;
                        2)
			check_args
                        subtract
                        ;;
                        3)
			check_args
                        multiply
                        ;;
                        4)
			check_args
                        divide
                        ;;
                        5)
                        exit
                        ;;
                esac
        done
}

check_args () {
echo "Please input a number"
read answer
number1=$answer
echo "Please input another number"
read answer
number2=$answer
if [ $number2 == 0 ]
then 
echo "Second number should not be 0"
break
fi
}

add() {
sum="$(($number1+$number2))"
echo "$sum is the sum"
}

subtract() {
difference="$(($number1-$number2))"
echo "$difference is the difference"
}

multiply() {
product="$(($number1*$number2))"
echo "$product is the product"
}

divide(){
if [ $number2 == 0 ]
then
echo "Second number should not be 0"
fi
quotient="$(($number1/$number2))"
echo "$quotient is the quotient"
}

# mainfunction

calc_menu
